const EMITTER_CONSTANTS = {
  NEW_CARE_PLAN: 'NEW_CARE_PLAN',
  CARE_PLAN_UPDATED: 'CARE_PLAN_UPDATED',
  CARE_PLAN_ASSIGNEE_CHANGED: 'CARE_PLAN_ASSIGNEE_CHANGED',
  UPDATED_REPORT: 'UPDATED_REPORT',
  NOTIFICATIONS: 'NOTIFICATIONS',
  TIMESHEET: 'TIMESHEET',
  EVENT_LOG: 'EVENT_LOG',
  APPOINTMENT: 'APPOINTMENT',
  LOGOUT: 'LOGOUT',
};

export default EMITTER_CONSTANTS;
